### ISSUE TITLE
import: Exception message:VS403113: A group with label 'Details' already exists in page 'Details'.

### ISSUE THREAD

**Issue by viperx77** [microsoft/process-migrator#30]
Process does not exist before attempting import.

```
[VERBOSE] [2019-01-09T19:53:11.688Z] Begin step 'Create group '04978aea-1160-4579-a4f9-2d4f68678af9' in page 'Scrum.Bug.Bug''.
[VERBOSE] [2019-01-09T19:53:11.792Z] Exception message:VS403113: A group with label 'Details' already exists in page 'Details'.
```

Relevant process.json section:

```
{
                "id": "Section2",
                "groups": [
                  {
                    "id": "04978aea-1160-4579-a4f9-2d4f68678af9",
                    "label": "Details",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "System.CreatedDate",
                        "label": "Found On",
                        "controlType": "DateTimeControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "PhilipsScrum.FoundBy",
                        "label": "Found By",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "7136ebcf-91cc-4724-980e-9e944e6e5ccd",
                        "label": "Module",
                        "readOnly": false,
                        "visible": true,
                        "contribution": {
                          "contributionId": "PhilipseICU.vsts-rest-picklist-control.picklist-form-control",
                          "inputs": {
                            "FieldName": "Custom.Module",
                            "Url": "https://dev.azure.com/patientcareanalytics/eICU/_apis/git/repositories/ALM/items?scopepath=GlobalLists.json&version=master ",
                            "Property": "$.Modules[*]",
                            "IsTreeView": "true"
                          }
                        },
                        "isContribution": true
                      },
                      {
                        "id": "48923dc1-0e1b-4a4a-bef3-107a2dd9fd6f",
                        "label": "Version Found",
                        "readOnly": false,
                        "visible": true,
                        "contribution": {
                          "contributionId": "PhilipseICU.vsts-rest-picklist-control.picklist-form-control",
                          "inputs": {
                            "FieldName": "PhilipsScrum.VersionFound",
                            "Url": "https://dev.azure.com/patientcareanalytics/eICU/_apis/git/repositories/ALM/items?scopepath=GlobalLists.json&version=master",
                            "Property": "$.ProductVersions[*]"
                          }
                        },
                        "isContribution": true
                      },
                      {
                        "id": "b4f8efa0-4f99-4999-84f6-a9cb294dbb1f",
                        "label": "Versions Where Present",
                        "readOnly": false,
                        "visible": true,
                        "contribution": {
                          "contributionId": "PhilipseICU.vsts-rest-picklist-control.picklist-form-control",
                          "inputs": {
                            "FieldName": "PhilipsScrum.VersionsWherePresent",
                            "Url": "https://dev.azure.com/patientcareanalytics/eICU/_apis/git/repositories/ALM/items?scopepath=GlobalLists.json&version=master",
                            "Property": "$.ProductVersions[*]",
                            "IsMultiSelect": "true"
                          }
                        },
                        "isContribution": true
                      },
                      {
                        "id": "PhilipsScrum.PLCStage",
                        "label": "PLC Stage",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "PhilipsScrum.IncidentSource",
                        "label": "Incident Source",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "PhilipsScrum.RequirementID",
                        "label": "Requirement ID",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "Custom.PreviousTFSID",
                        "label": "Previous TFS ID",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      }
                    ]
                  },
                  {
                    "id": "dcacc634-c5a4-44e6-86b6-fb08d2df17cd",
                    "label": "Complaint Info",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "PhilipsScrum.ReportingCustomer",
                        "label": "Reporting Customer",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      },
                      {
                        "id": "PhilipsScrum.SupportTicket#",
                        "label": "Support Ticket #",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "visible": true,
                        "isContribution": false
                      }
                    ]
                  },
                  {
                    "id": "Scrum.Bug.Bug.Details",
                    "inherited": true,
                    "overridden": true,
                    "label": "Version Found",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "Microsoft.VSTS.Common.Priority",
                        "inherited": true,
                        "overridden": true,
                        "label": "Priority",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      },
                      {
                        "id": "Microsoft.VSTS.Common.Severity",
                        "inherited": true,
                        "overridden": true,
                        "label": "Severity",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      },
                      {
                        "id": "Microsoft.VSTS.Scheduling.Effort",
                        "inherited": true,
                        "overridden": true,
                        "label": "Effort",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      },
                      {
                        "id": "Microsoft.VSTS.Scheduling.RemainingWork",
                        "inherited": true,
                        "overridden": true,
                        "label": "Remaining Work",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      },
                      {
                        "id": "Microsoft.VSTS.Common.Activity",
                        "inherited": true,
                        "overridden": true,
                        "label": "Activity",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      }
                    ]
                  },
                  {
                    "id": "Scrum.Bug.Bug.Build",
                    "inherited": true,
                    "overridden": true,
                    "label": "Defect Review",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "Microsoft.VSTS.Build.FoundIn",
                        "inherited": true,
                        "overridden": true,
                        "label": "Found in Build",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      },
                      {
                        "id": "Microsoft.VSTS.Build.IntegrationBuild",
                        "inherited": true,
                        "overridden": true,
                        "label": "Integrated in Build",
                        "controlType": "FieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": false,
                        "isContribution": false
                      }
                    ]
                  }
                ]
              }
```

**Comment by liang2zhu1** [comment]
@viperx77 Thanks for reporting this I'm investigating this and based on the process.json, it appears to me you have renamed the built-in 'Details' tab to "Version Found" and created another group with name 'Details' is that correct?

**Comment by viperx77** [comment]
Yes, that is correct.

**Comment by liang2zhu1** [comment]
This was fixed in https://github.com/microsoft/process-migrator/pull/34

**Comment by prashanthbv12** [comment]
I am still getting below error after downloading latest code. Please help

[VERBOSE] [2019-10-17T11:12:16.203Z] Exception message:VS403113: A group with label 'Details' already exists in page 'Details'.
Call stack:Error: VS403113: A group with label 'Details' already exists in page 'Details'.
    at RestClient.<anonymous> (C:\Users\prashanth.v\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\prashanth.v\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] [2019-10-17T11:12:16.204Z] Import failed, see log file for details. Failed to edit group 'Scrum.Epic.Epic.Status' in page 'Scrum.Epic.Epic', see logs for details.
